export const TEXT = {
	appName: "Monexo",
	appVersion: "FinForecast v1.0.0",

	nav: {
		forecast: "Previsao",
		transactions: {
			incomes: "Ganhos",
			expenses: "Gastos",
		},
		settings: "Ajustes",
	},
	header: {
		forecast: "Monexo",
		transactions: {
			incomes: "Ganhos",
			expenses: "Gastos",
		},
		settings: "Ajustes",
	},

	auth: {
		loginTitle: "Faca login para continuar",
		registerTitle: "Criar Conta",
		registerSubtitle: "Preencha os dados para comecar",
		emailLabel: "Email",
		emailPlaceholder: "seu@email.com",
		passwordLabel: "Senha",
		passwordPlaceholder: "Sua senha",
		confirmPasswordLabel: "Confirmar Senha",
		confirmPasswordPlaceholder: "Digite sua senha novamente",
		nameLabel: "Nome",
		namePlaceholder: "Seu nome completo",
		loginButton: "Entrar",
		registerButton: "Criar Conta",
		haveAccount: "Ja tem uma conta?",
		noAccount: "Nao tem uma conta?",
		signIn: "Fazer Login",
		signUp: "Cadastrar-se",
		usernameLabel: "Nome de usuario",
		usernamePlaceholder: "Como quer ser chamado",
		passwordHint: "Minimo 8 caracteres, com maiuscula, minuscula e numero",
		errorFillFields: "Preencha todos os campos",
		errorPasswordMismatch: "As senhas nao conferem",
		errorPasswordLength: "A senha deve ter pelo menos 8 caracteres",
		errorPasswordWeak:
			"A senha precisa de ao menos uma letra maiuscula, uma minuscula e um numero",
		errorLogin: "Erro ao fazer login",
		errorRegister: "Erro ao criar conta",
	},

	settings: {
		title: "Ajustes",
		defaultUser: "Usuario",
		defaultEmail: "usuario@email.com",

		sectionAccount: "CONTA",
		sectionPreferences: "PREFERENCIAS",
		sectionSupport: "SUPORTE",
		sectionSession: "SESSAO",

		profile: "Perfil",
		profileSubtitle: "Editar informacoes pessoais",
		notifications: "Notificacoes",
		notificationsSubtitle: "Configurar alertas",
		security: "Seguranca",
		securitySubtitle: "Senha e autenticacao",

		currency: "Moeda",
		currencySubtitle: "BRL - Real Brasileiro",
		darkMode: "Modo Escuro",
		darkModeOn: "Ativado",
		darkModeOff: "Desativado",
		language: "Idioma",
		languageSubtitle: "Portugues (Brasil)",

		help: "Ajuda",
		helpSubtitle: "Perguntas frequentes",
		contact: "Contato",
		contactSubtitle: "Fale conosco",
		terms: "Termos de Uso",
		privacy: "Politica de Privacidade",

		logout: "Sair",
		deleteAccount: "Excluir Conta",

		logoutConfirmTitle: "Sair",
		logoutConfirmMessage: "Deseja sair da sua conta?",
		deleteConfirmTitle: "Excluir Conta",
		deleteConfirmMessage:
			"Tem certeza que deseja excluir sua conta? Esta acao nao pode ser desfeita.",
		cancel: "Cancelar",
		confirmLogout: "Sair",
		confirmDelete: "Excluir",
	},

	transactions: {
		title: "Transacoes",
		searchPlaceholder: "Buscar transacoes...",
		errorLoad: "Erro ao carregar transacoes",
		emptyTitle: "Nenhuma transacao encontrada",
		emptyMessage: "Adicione sua primeira transacao",
		addButton: "Nova Transacao",
		deleteTitle: "Excluir",
		deleteMessage: "Deseja excluir esta transacao?",
		deleteFailed: "Nao foi possivel excluir a transacao",
	},

	form: {
		newTitle: "Nova Transacao",
		editTitle: "Editar Transacao",
		type: "Tipo",
		date: "Data",
		description: "Descricao",
		descriptionPlaceholder: "Ex: Salario, Aluguel...",
		amount: "Valor (R$)",
		amountPlaceholder: "0,00",
		method: "Metodo de pagamento",
		frequency: "Frequencia",
		installment: "Parcelas",
		installmentPlaceholder: "Ex: 12",
		installmentHint: "Deixe vazio para nao parcelar (minimo 2 parcelas)",
		bank: "Banco",
		bankPlaceholder: "Ex: Nubank",
		card: "Tipo de cartao",
		datePickerDone: "Concluir",
		errorDescriptionRequired: "Informe uma descricao",
		errorAmountRequired: "Informe um valor maior que zero",
		errorBankRequired: "Informe o banco do cartao",
		errorInstallmentInvalid: "O numero de parcelas deve ser maior que uma",
	},

	forecast: {
		title: "Monexo",
		header: "Projeção Mensal",
		errorLoad: "Erro ao carregar previsao",
		empty: "Nenhuma projecao disponivel para este periodo.",
		period: "Periodo",
		totalIncome: "Receita Total",
		totalExpense: "Despesa Total",
		netBalance: "Saldo Líquido",
		currentBalance: "Saldo Atual",
		finalBalance: "Saldo Final",
		selectPeriod: "Selecionar Período",
	},

	common: {
		loading: "Carregando...",
		error: "Erro",
		warning: "Atencao",
		success: "Sucesso",
		save: "Salvar",
		cancel: "Cancelar",
		delete: "Excluir",
		edit: "Editar",
		add: "Adicionar",
		search: "Buscar",
		filter: "Filtrar",
		close: "Fechar",
		ok: "OK",
		yes: "Sim",
		no: "Nao",
	},

	errors: {
		network: "Erro de conexao",
		unknown: "Erro desconhecido",
		timeout: "Tempo de espera excedido",
		unauthorized: "Nao autorizado",
		sessionExpired: "Sua sessao expirou. Faca login novamente.",
		notFound: "Nao encontrado",
		serverError: "Erro no servidor",
		tryAgain: "Tente novamente",
	},
} as const;

export type TextKeys = typeof TEXT;
